name: CKMPAK
options:
    bundleIdPrefix: org.opengamestudio
targets:
    Sample:
        type: application
        platform: iOS
        deploymentTarget: "16.0"
        sources:
            - path: "../src"
        settings:
            base:
                INFOPLIST_FILE: Info.plist
